# Generated by Django 5.1.3 on 2025-02-04 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('residence', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField()),
                ('etat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mode_paiement', models.CharField(max_length=100)),
                ('etat', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('Panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lastapp.panier')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantité_total', models.IntegerField()),
                ('prix_total', models.FloatField()),
                ('Statut', models.CharField(max_length=255)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lastapp.client')),
                ('Panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lastapp.panier')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('prix_unitaire', models.FloatField(null=True)),
                ('quantité_stock', models.IntegerField(null=True)),
                ('Statut', models.CharField(max_length=100)),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lastapp.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=100)),
                ('montant', models.FloatField()),
                ('operateur', models.CharField(max_length=255)),
                ('dateoperation', models.DateField()),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lastapp.client')),
            ],
        ),
    ]
