# Generated by Django 5.1.3 on 2025-02-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lastapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='Produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Lastapp.produit'),
        ),
    ]
