# Generated by Django 5.1.3 on 2025-02-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lastapp', '0002_achat_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='nomPanier',
            field=models.CharField(default='', max_length=255),
        ),
    ]
