# Generated by Django 5.1.3 on 2025-02-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lastapp', '0003_panier_nompanier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='Statut',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='quantité_stock',
        ),
        migrations.AlterField(
            model_name='achat',
            name='Statut',
            field=models.BooleanField(null=True),
        ),
    ]
