# Generated by Django 5.1.3 on 2025-02-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lastapp', '0004_remove_produit_statut_remove_produit_quantité_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMode', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='facture',
            name='mode_paiement',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='operateur',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Operateur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Lastapp.operateur'),
            preserve_default=False,
        ),
    ]
