# Generated by Django 5.1.3 on 2025-02-06 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lastapp', '0005_modepaiement_operateur_remove_facture_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='ModePaiement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Lastapp.modepaiement'),
            preserve_default=False,
        ),
    ]
