# Generated by Django 5.1.3 on 2025-02-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Lastapp", "0006_facture_modepaiement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achat",
            name="Statut",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
