# Generated by Django 5.1.3 on 2025-02-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Lastapp", "0008_remove_achat_produit_produit_achat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="Achat",
        ),
        migrations.AddField(
            model_name="achat",
            name="Produit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Lastapp.produit",
            ),
        ),
    ]
